---
title: "Examples of vowel change plots (using TIMIT labels)"
output: html_document
---

```{r setup include=FALSE}
library(plyr)
library(magrittr)
library(rphonch)
library(ggplot2)
color_palette <- c("#E69F00", "#56B4E9", "#CC79A7", "#D55E00",
                   "#0072B2", "#D55E00")
names(color_palette) <- c("IY", "UW", "AA", "AE", "EH", "OW")
```

```{r load, include=FALSE}
rep_dirs <- list.dirs("../reps/", full.names=T, recursive=F)
names(rep_dirs) <- list.dirs("../reps/", recursive=F, full.names=F)
reps_l <- list()
reps_spkr_l <- list()
for (r in names(rep_dirs)) {
  r_files <- dir(rep_dirs[r], pattern="*.rep", full.names=T)
  r_meta <- read.csv(paste0(rep_dirs[r], "/meta_info.csv"))
  r_reps <- ldply(r_files, .fun=read_rep)
  r_reps <- ddply(r_reps, .(speaker_id), transform,
                  X0=(X0-mean(X0, na.rm=T))/sd(X0, na.rm=T))
  r_reps$rep <- r
  r_reps <- split_vowel_and_stress(r_reps)
  r_reps_spkr <- ddply(r_reps, .(speaker_id, phoneme, stress, rep),
                       summarize, X0=mean(X0))
  reps_l[[r]] <- merge(r_reps, r_meta)
  reps_spkr_l[[r]] <- merge(r_reps_spkr, r_meta)
}
reps <- do.call("rbind", reps_l)
reps_spkr <- do.call("rbind", reps_spkr_l)
```

Back vowels
------

```{r back-vowels}
d <- reps %$% reps[phoneme %in% c("UW","OW","AA","IY") &
                   stress %in% c("S1", "S2"),]
p <- ggplot(d, aes(x=dob, y=X0, colour=phoneme)) +
      geom_smooth(lwd=3) +
      theme(text=element_text(size=20)) +
      xlab("Date of birth") +
      facet_wrap(~ rep, scales="free_y", shrink=T)
print(p)
```

```{r back-vowels-spkr}
d <- reps_spkr %$% reps_spkr[phoneme %in% c("UW","OW","AA","IY") &
                             stress %in% c("S1", "S2"),]
p <- ggplot(d, aes(x=dob, y=X0, colour=phoneme)) +
      geom_smooth(lwd=3) +
      theme(text=element_text(size=20)) +
      xlab("Date of birth") +
      facet_wrap(~ rep, scales="free_y", shrink=T)
print(p)
```


Front lax vowels
------

```{r front-lax-vowels}
d <- reps %$% reps[phoneme %in% c("IY","IH","EH","AE", "AA") &
                   stress %in% c("S1", "S2"),]
p <- ggplot(d, aes(x=dob, y=X0, colour=phoneme)) +
      geom_smooth(lwd=3) +
      theme(text=element_text(size=20)) +
      xlab("Date of birth") +
      facet_wrap(~ rep, scales="free_y", shrink=T)
print(p)
```

```{r front-lax-vowels-spkr}
d <- reps_spkr %$% reps_spkr[phoneme %in% c("IY","IH","EH","AE", "AA") &
                             stress %in% c("S1", "S2"),]
p <- ggplot(d, aes(x=dob, y=X0, colour=phoneme)) +
      geom_smooth(lwd=3) +
      theme(text=element_text(size=20)) +
      xlab("Date of birth") +
      facet_wrap(~ rep, scales="free_y", shrink=T)
print(p)
```
